### ISSUE TITLE
itz auth login command suggestion wrong global flag

### ISSUE THREAD

**Issue by RapTho** [cloud-native-toolkit/itzcli#2]
I ran the following command

`itz doctor init`

It failed and suggested following command

`itz auth login --from-file /path/to/token.txt --service builder`

Unfortunately, this suggestion also fails, becuase --service is an unknown global flag. Maybe --service-name is the correct one?

`itz auth login --from-file /path/to/token.txt --service-name builder`

See Screenshot
![image](https://user-images.githubusercontent.com/48417580/208707116-09ee5def-75b8-48d2-99f6-bace6f407140.png)

**Comment by nathanagood** [comment]
This feature has changed from how this works specifically, but I believe this will be now addressed in the 1.0 release (upcoming).
